# Generated by Django 2.0.6 on 2018-06-28 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='save_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='save date'),
            preserve_default=False,
        ),
    ]
