# Generated by Django 2.0.6 on 2018-06-28 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_expenses_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.TypeExpense'),
        ),
    ]
